swcarpentry/r-novice-gapminder

- 07-functions.Rmd
> callout defining function

- 05-data-structures-part2.Rmd
Modifications to the data frames/lists tutorial
Among the changes:
1. Emphasize cbind rather than rbind, with the idea that column
additions are likely to be more common
2. Show how to add a factor level so that rbind example will work
3. Challenge covering `names` vs `colnames`
The discussion of the gapminder csv file remains, even though there is
now a gapminder package. It would probably be good to change to using the
package.
> Change to data frames/lists tutorial

- 01-rstudio-intro.Rmd
The text for the first tip started on the same line as the title and `{.callout}`, causing the tip to not display properly.
vs.
> Fix format of first tip in RStudio section

- 01-rstudio-intro.Rmd
The Interface in RStudio does not have `Workspace` anymore but `Environment`. Also since some time there is `Viewer` tab in bottom right pane by default.
> Update names used in RStudio interface

- 08-plot-ggplot2.Rmd
The example code under *Modifying Text* uses `scale_fill_discrete()` to change the label on the legend from "continent" to "Continent". However this doesn't work, because it is a color scale. The fix is to change to `scale_colour_discrete(name="Continent")`.
> fix legend label error

- 06-data-subsetting.Rmd
I made the following changes to the callout on logical operators:
* In the title, "chain" becomes "combine": my impression is that the word "chain" is not commonly used as a verb by non-programmers
* In the title, "operations" becomes "conditions": this section mostly talks about combining the `TRUE`s and `FALSE`s themselves, rather than the operations such as `>` that produced them.
* Add an example for why we'd want to combine multiple logical vectors
* Fix an incorrect statement regarding `&&` and `||`'s recycling behavior
* Add logical negation, `all`, and `any`.
If the section is too long now, I'd suggest dropping the double operators (`&&` and `||`) first, then `all` and `any` if needed..
> update 06-subsetting on logical operations

- _includes/footer.html
Change footer link 'Source' from the workshop template to the lesson repo at https://github.com/swcarpentry/r-novice-gapminder
> Fix footer 'Source' link

- 08-plot-ggplot2.Rmd
Per issue #100 , I switched the axes of some of the graphs so GDP per capita is a _predictor_ for life expectancy.  The knit'd .html was not committed (per .gitignore & point 3 of guidelines), so that would need to be added.
> Switch x and y axis so lifeExp on y, gdpPercap on x

- 08-plot-ggplot2.Rmd
Multi-panel figures were just a bit too cluttered when using the entire gapminder data set.  This change uses a subset of those data (countries starting with letter A or Z).  The goals of the subset were to (1) make the figure a bit more readable, (2) ensure all continents were represented (Oceania is a pain), (3) keep it nice by having a full matrix of graphs ("A" alone creates 7 graphs, resulting in two rows of three, and one row of one, less than pretty).  An alternative for a single letter would be "C" (4 x 4), but only four continents are represented (@#$* Oceania).
> Subset data for multi-panel figures

- 06-data-subsetting.Rmd
Data subsetting invokes an error with `x[-1:3]`, but lesson language pointed out error _after_ it showed up on the page.  Updated Rmd to (1) show the code that would produce the error, (2) point out that there is an error, (3) show the actual error.  Also added a `error=FALSE` in matrix subsetting section that was prefenting knitr from working.
> Rearrange error code so it matches lesson order

- 14-tidyr.Rmd
Added R code to load the gap_wide dataset in Data Manipulation with tidyr.
This dataset is referenced in the lesson without being loaded.
Loading the data with read.csv() causes problems later (see #94) because
columns are loaded as Factor not chr.
Loading the dataset with stringsAsFactors = FALSE (referenced in comments on line 26 of the Rmd)
fixes the problem and the all.equal() function works as intended.
Columns 37 and 38 are still imported as int instead of num, but this does not lead to problems.
> Load the gap_wide dataset for tidyr lesson

- 15-knitr-markdown.Rmd
This is to maintain consistency with other lessons and to reduce warnings from `make check`.
> Reduced knitr lesson header levels from h3 to h2 

- 07-control-flow.Rmd
The second Tip in the lesson (any and all) was not being formatted correctly.  I added an empty line between the tip header and content in an effort to get the formatting to work (thumb-tack image, blue box, etc.).
> Add line for appropriate Tip formatting

- _episodes_rmd/05-data-structures-part2.Rmd
Because
~~~
> ?cbind  # Work
> ?rbind  # Work
> ?omit  # Fail with the following message
No documentation for ‘omit’ in specified packages and libraries:
you could try ‘??omit’
> ?na.omit  # Work
~~~
> Make key points more specifics

- fig/13-dplyr-generate-figures.R
- fig/14-tidyr-generate-figures.R
Changed DiagrammeR font from Times New to Courier for all three figures in episode 13 - dplyr. Also split label for fig 3 across three rows to make it more 'dplyr-like'. Fixes issue #208
> Changed DiagrammeR label font

- _episodes_rmd/03-seeking-help.Rmd
There is a trailing backtick in the third example vector of challenge 1 in episode 3. On verbatim execution in R this prohibits the correct execution of the c() function, instead leading to an R prompt expecting further input.
> Episode 3, challenge 1: trailing backtick breaks example 

- reference.md
This is the current page:
http://swcarpentry.github.io/r-novice-gapminder/reference/
Hopefully, it won't do that anymore.
> Fix weird title rendering

- _episodes_rmd/06-data-subsetting.Rmd
When I was going over lesson 06 for subsetting data, I got a little confused by why the example illustration jumped back to the initial x vector assignment c("a", "b", "c", "d", "e"). I thought it would be better for continuity if the example illustration used the x vector previously assigned c("a", "a", "a") and went over what happens with you %in% with c("a", "c").
> Modified illustration example to fit previous example better.

- _episodes_rmd/04-data-structures-part1.Rmd
For my instructor checkout I've given this lesson a basic proof and copy edit. It includes a handful of grammatical or styles changes to make it read more smoothly and correct one or two typos. The section on read.table/read.delim/read.csv has been rewritten.
Change notes by line:
35: "like what you might already have" not very natural english, not typically regarded as valid for (formal) written text
66: Updated the read.table/read.csv/read.delim description to correctly reflect who and why R provides these functions
156: "When R reads a csv file" - corrected the article
231: removed double 'that' for clearer reading
245: grammatical change to "such as" to clarify example is being given
310: moved c() to it's own clause and made explicit that we are talking about a function.
404: …
> Proof and copy edit for 04-data-structures-part1.Rmd

- _episodes_rmd/04-data-structures-part1.Rmd
'Research Bazaar' seems a holdover from previous lesson contributors, changed to be more generic.
> Replace list example title

- _episodes_rmd/13-dplyr.Rmd
Link to http://r4ds.had.co.nz/ in the dplyr lesson (episode 13) was incomplete.
> Fix link to R for Data Science in dplyr lesson

- _episodes_rmd/01-rstudio-intro.Rmd
The output of the command ls() on line 397 shows two variables, x and y. But (confusingly) there is no place that the y variable is defined in the current lesson. This simple change will make the output of ls() consistent for anyone who is following along exactly.
> define variable 'y'

- _episodes_rmd/02-project-intro.Rmd
Information on installing and configuring Git with R Studio is missing.  Since Git is a cursory part of this lesson, this proposed file change will remove Git references and replace with link to better version of content in SWC Git lesson.
https://github.com/swcarpentry/r-novice-gapminder/issues/275
> Git Removal and Add Link

- _episodes_rmd/06-data-subsetting.Rmd
intervening changes in `x` messed up the example. Redefining it is safer.
> redefine x so skipping-named-elements works

- _episodes_rmd/03-seeking-help.Rmd
The closing `{: .solution}` for challenge 3 is missing a `.`. This breaks the interactive display of the solution. I'm adding the missing `.`.
> Fix interactive display for challenge 3

- CONTRIBUTING.md
Links in CONTRIBUTING.md were 404's (previously https://github.com/swcarpentry/FIXME and https://github.com/swcarpentry/FIXME/issues/).
> Updated links for both issues and main repo

- _episodes/14-tidyr.md
Typographic changes made the following things consistent:
* spaces after commas in function calls
* backticks when referring to packages, functions, and variable/column names
* numerals expressed in words when they are less than 10
* capitalization convention of "observation variables"
I've also rewritten some sentences/paragrahs to make the sentence logic clearer.
(Since some of the edits required reflowing the paragraphs, I recommend viewing this with `git diff --word-diff`.)
> Ensure typographic consistency + reformulate sentences

- _episodes_rmd/07-control-flow.Rmd
removed comments about "Poisson distribution" and "lamda = 8" that we left over when 
`x <- rpois(1, lambda=8)` was changed to `x <- 8` in 
https://github.com/swcarpentry/r-novice-gapminder/commit/f60708b030f3c4479536476c3647080adfee129c
> remove out of date comment in 07-control-flow.Rmd

- _episodes_rmd/01-rstudio-intro.Rmd
Remove spurious newline, which was preventing the callout rendering correctly
> Fix markdown fomatting in episode 1

- _episodes_rmd/16-wrap-up.Rmd
Project folder structure section (and `ProjectTemplate` example) was moved from [Project Management With RStudio](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/), as it's more appropriate for advanced users, see #379.
> Added project folder structure section

- _episodes_rmd/05-data-structures-part2.Rmd
In 'Exploring Data Frames', changed the name of the vector created in Challenge 1 from 'human.age' to 'human_age'. This should resolve issue #383. @naupaka
> Exploring Data Frames -- changed 'human.age' to 'human_age'

- _episodes_rmd/01-rstudio-intro.Rmd
This is causing issues with recent upstream changes to the script building the lessons. Running `rm()` removes variables that are needed by the script.
> don't evaluate rm() during rendering

- _episodes/02-project-intro.md
- _episodes_rmd/02-project-intro.Rmd
In RStudio it is shown "New Project", not "Empty Project".
In the .md file the link is wrong. It links to gapminder_wide.csv. It is correct in the .Rmd file. It is also correct in the Episode Exploring data Frames.
> changed to "New Project"; correct link to gapminder_data.csv

- _episodes_rmd/05-data-structures-part2.Rmd
This pull request is intended to resolve #420 by adding some text reflecting on the results of using `rbind` with factors.  By examining the object (`cats`), the learner can note the unusual results following the warning about factor levels (successful `rbind` but introduction of `NA`), which may better set up the subsequent discussion about what factors are.
> Clarify warning vs error of rbind

- _episodes_rmd/15-knitr-markdown.Rmd
The link to the knitr site was formatted as in-line R code, so reformatted as a link
> fixed formatting for link to knitr site

- _episodes_rmd/15-knitr-markdown.Rmd
*Following up on a previous PR (https://github.com/swcarpentry/r-novice-gapminder/pull/486)*
I think some of the text in this lesson was written based on a previous version of the RStudio IDE. This Pull Request has two changes:
1. The new RStudio just has a "Knit" button, not "Knit HTML" as in the lesson.
2. There is no question mark next to the Knit button; instead, the Markdown reference is listed under the Help menu of the toolbar. I also added text to point readers to the R Markdown Cheat Sheet, which is directly accessible from Rstudio
> Rstudio updates

- _episodes_rmd/15-knitr-markdown.Rmd
*Following up on a previous PR (https://github.com/swcarpentry/r-novice-gapminder/pull/487)*
This commit moves the links to the knitr homepage out of backticks (so that they are click-able), and adds a link specifically to the broman package
> fixes backticks when linking to packages, fixes link to broman package

- _episodes_rmd/08-plot-ggplot2.Rmd
Per #502 , removing `color=continent` at beginning of Transformations & Statistics section in order to maintain continuity with subsequent portions of the lesson.
> Remove color from Transformations & statistics (08)

- _episodes_rmd/08-plot-ggplot2.Rmd
- _episodes_rmd/16-wrap-up.Rmd
Call to `ProjectTemplate::create.project` will throw error if a project "my_project" already exists in the parent directory. This PR changes the name of the project to "my_project2" in attempt to avoid collision.
> Update ProjectTemplate code to remove potential conflict

- _episodes_rmd/05-data-structures-part2.Rmd
- _episodes_rmd/13-dplyr.Rmd
CRAN [asks people](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-URLs) to use this URL variant when linking to packages ;-) This PR results from a semi-automatic search-and-replace script and implements their suggestion.
> Canonicalize CRAN links

- README.md
This PR simply adds the Binder button to the README. The Binder instance will be built using the material in the `binder` branch provided by PR #531.
> added binder button to README

- _episodes_rmd/15-knitr-markdown.Rmd
In Rmarkdown, backticks specifying inline-code formatting take precedence over square brackets used for inserting a hypertext link. Thus the backticks should be inside the square brackets rather than around the entire statement.
Otherwise the knitted document shows the literal string instead of being a clickable link.
> Fixed broken link caused by misplaced backticks

- _episodes_rmd/08-plot-ggplot2.Rmd
for creating a multi-panel figure, the data is subsetted to only those beginning with A or Z.  The method applied is creative but very challenging!  It doesn't add much to the exercise, which is obviously focused on the capabilities of ggplot2 rather than interesting shortcuts for data subsetting.  I'm proposing a simple subsetting based on matching one of the variables (continent), a strategy which is applied earlier in the workshop.
> Simplifying the section on Multi-panel figures

- _episodes_rmd/15-knitr-markdown.Rmd
This is more of an issue/bug-report, but because of a related fix.
The sub- & superscript examples seem to [not be rendered online](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html#a-bit-more-markdown), but are rendered when using RStudio's knitr button.
Thus our code is fine here (with the fix), but the lesson template somehow doesn't render it.
> Correct sub- & superscript formatting

- _episodes_rmd/05-data-structures-part2.Rmd
This pull request is to address[ issue 561](https://github.com/swcarpentry/r-novice-gapminder/issues/561) regarding the `%in%` operator. I copied the relevant text from Episode 6 and added to Episode 5. (This is my first Carpentries contribution and I am not very git savvy - please let me know if I need to do anything differently!) Thanks.
> Edited Episode 5 to address issue 561

- _episodes_rmd/01-rstudio-intro.Rmd
The links for downloading R and RStudio appear on the same line with no punctuation between them In the [Before Starting the Workshop](http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/#before-starting-the-workshop) section of the first lesson.
I think this could be confusing for users since it looks like one link where there's actually two. Here's a screenshot of the problem with the two links underlined separately in red:
I think the intention was probably to have these on separate lines or as bullets, since they appear on separate lines in the R Markdown file.
This pull requests adds unordered bullets to separate these instructions onto separate lines. The output looks like this:
I've checked the issues and PRs for this problem, but didn't find anything.
> Separate R and RStudio download links with unordered bullets

- _episodes_rmd/08-plot-ggplot2.Rmd
There are blank lines in challenges 4b and 5, which mean that the episode does not display correctly. This edit removes those blank lines.
I've also edited to "Here *is* a possible solution" rather than "Here a possible solution" because I'm a bit of a grammar pedant :-)
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all …
> Remove blank lines breaking challenge formatting

- _episodes_rmd/02-project-intro.Rmd
Addressing #600 
Contributions:
- Added paragraph on opening .Rproj files after they have been created
- Fix numbering for Challenges
- Add Challenge for opening an .Rproj file (might be redundant)
- Revised text for command line tip to reflect that a Terminal has been present directly in RStudio for several versions.
Proposed contribution not yet committed:
- I am wondering if you'd consider adding a `.gitattributes` file that specifies that this repo is an R repo. Currently the repo, based on code within it, is a Python repo. This might be confusing for students who find themselves at this repo.
> Navigating to .Rproj files

- _episodes_rmd/01-rstudio-intro.Rmd
Added an explanation of why `ls` without parens prints the contents of the ls object.
This should fix issue #623 
`make serve` didn't want to render until I renamed a duplicate code block in one of the challenge solutions.
> Explain object printing behavior

- .travis.yml
- tic.R
@jcoliver this is to fix the R version during the build process to R 3.6.3.
> fix R version to use R old-release

- _episodes_rmd/06-data-subsetting.Rmd
Replaces example using `iris` dataset with example using `mtcars` dataset to avoid using data created by a eugenicist.
> Repace iris with mtcars

- _episodes_rmd/10-functions.Rmd
- _extras/about.md
- _extras/discuss.md
- _extras/guide.md
- reference.md
- setup.md
See discussion here for more background: https://github.com/datacarpentry/datacarpentry.github.io/issues/542
In short, some Carpentries lessons use the path `/guide/` for their Instructor Notes page and others use `/guide/index.html` (the default defined in `_config.yml`). This PR removes permalinks with a trailing slash from the YAML front matter of the Instructor Notes (`_extras/guide.md`) and other Extras files, consistent with new lessons created with [the lesson template](https://github.com/carpentries/styles/). Although there's no functional difference in the online versions of the lesson pages, pages with a trailing slash in the permalink will result in **broken links in the version of the lesson built locally**. We'd like local builds to be usable e.g. in workshops taking place at …
> make lesson suitable for teaching with locally-built (serverless) pages

- _config.yml
_config.yml did not have definition of CC BY 4.0 license link (but bin/boilerplate/_config.yml did). Added definition to _config.yml so link is correctly resolved on footers of pages.
> Add CC BY 4.0 link to _config.yml

- _episodes_rmd/04-data-structures-part1.Rmd
- _episodes_rmd/05-data-structures-part2.Rmd
A stopgap measure to ensure `read.csv` reads in character data (as factor) regardless of R version. This PR only adds fixes for episodes 4 and 5; `read.csv` is used elsewhere (episodes 6-14), but should not create significant differences in behavior for different R versions.
> Add stringsAsFactors = TRUE

- _episodes_rmd/04-data-structures-part1.Rmd
- _episodes_rmd/05-data-structures-part2.Rmd
Stopgap for differential behavior of `read.csv` in versions >= 4.0. Replacement PR for #678, which pulled against wrong branch.
> Add stringsAsFactors = TRUE for ep. 04 & 05

- _episodes_rmd/08-plot-ggplot2.Rmd
This pull request follows from issue #688  and revises a figure description in episode 08. The old description mentions a function name that is not used in the example above (log10 versus scale_x_log10. The new description includes the scale_x_log10 function name and tries to clarify what the function does.
> update reconcile text describing scale log10 transformation with plot

- bin/lesson_check.py
This should address the issue from https://github.com/swcarpentry/r-novice-gapminder/pull/696#issuecomment-796265728 and reveal all of the formatting issues that need to be addressed for make check to pass.
> Update styles 

- _episodes_rmd/14-tidyr.Rmd
A second attempt at fixing a small typo, changing `gap_wide_betterID` at line 36 to `gap_wide` to write the correct variable to the .csv file. As suggested in the comment on the previous pull request #691  I also added quotes to the tittle and pulled against the master branch this time. I did not use styler to style anything this time as it seemed to introduce some problems. Hope this fixes the issues and thanks for your patience.
> fixes gap wide typo and adds quotes to title

- reference.md
Added  definition of `%in% operator to the `reference` page. 
Mentioned offhand in #603.
<details>
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a …
> Added %in% operator to /reference.html

- _episodes_rmd/13-dplyr.Rmd
Modified header to complete proposed change (https://github.com/swcarpentry/r-novice-gapminder/issues/712). The changed section is about "Using group_by()" and "Using summarize()" is in the next section, so this edit removes "and summarize()" as suggested by @abanihas and approved by @jcoliver
<details>
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be …
> Edit to header

- _episodes_rmd/11-writing-data.Rmd
Dot is not needed and its use is not introduced earlier in the lesson materials. Removed for simplicity.
Addresses issue #721.
> Remove unnecessary dot from facet_grid

- _episodes_rmd/03-seeking-help.Rmd
Fixes https://github.com/swcarpentry/r-novice-gapminder/issues/784 and other typos, and adds a few spelling, grammatical, and phrasing suggestions. The typo mentioned on that issue was in Episode 3, not 2.
> Grammatical Review for Episode 3

- _episodes_rmd/08-plot-ggplot2.Rmd
The "by" aesthetic in ggplot2 is no longer supported. Although it still works, it throws a warning like: 
`> ggplot(gapminder, aes(x=year,y=lifeExp)) +
geom_point(alpha=0.5) +
scale_x_log10() +
geom_line(aes(color=continent, by=country)) 
Warning message:
In geom_line(aes(color = continent, by = country)) :
Ignoring unknown aesthetics: by`
I can't find any documentation in the official reference (e.g. https://ggplot2.tidyverse.org/reference/index.html#aesthetics) for `by`. Instead, `group` is used.
I tried to update all code chunks with the `by` aesthetic and also change related text where I found it. I tried to search the remainder of the lessons and didn't find it anywhere.
<details>
If this contribution …
> Replace deprecated "by" aes with "group"

- _episodes_rmd/01-rstudio-intro.Rmd
I noticed that the output of the `ls()` function in Lesson 1 (RStudio intro) presently contains a number of extra items (`args`, `dest_md`, `op`, `src_rmd`) that learners shouldn't see on their end if following along in the lesson. This probably comes from the usage of the [`generate_md_episodes()`](https://github.com/swcarpentry/r-novice-gapminder/blob/6c0b1812d9b04c95ad8176ae18eb34a9d86ea65a/bin/generate_md_episodes.R) function, as noted in discussion of #178. The relevant code is on [line 448](https://github.com/swcarpentry/r-novice-gapminder/blob/4b5dbd88b97379f97c8c6a54762fe6461e1e8260/_episodes_rmd/01-rstudio-intro.Rmd#L448) of the Lesson 1 Rmd file.
I've implemented a surface-level solution by defining a temporary environment that contains only the variables that learners should …
> Fix output of ls() function in Lesson 1 RStudio intro

- episodes/05-data-structures-part2.Rmd
We removed the factors section of Data Structures Part 2 consistent with the changes made to Data Structure Part 1 which have already been merged. #737 
We recommend adding a section about factors to a lesson about plotting. 
This is related to Issue #633. 
@sstevens2
> Remove factors from 05-data-structures-part2.Rmd

- episodes/15-knitr-markdown.Rmd
Changed list description to clarify that to render correctly, there needs to be an empty line between some text and a list.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about …
> Add spaces between list and title

- episodes/02-project-intro.Rmd
In [this challenge to set the working directory](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro.html#challenge-5) two options are given --  to use the `setwd()` command or to use the option in the `Sessions` menu. 
There are two steps in using the `Sessions` menu.  The second step is displayed as a third item in the list.  This PR puts both steps in the same list item.
> clarify instructions to set working directory

- renv/activate.R
- renv/profiles/lesson-requirements/renv.lock
I've run the package update manually because the automated workflow was having trouble after the release of {renv} 1.0.0.
This brings in updates to 34 packages. Please wait for the output to run and then check for any new errors, warnings or surprising output changes.
I ran the following commands to update the cache with {renv} 1.0.2
```r
sandpaper::manage_deps()
sandpaper::update_cache()
```
```
- 34 packages have updates available.
- boot          [1.3-28 -> 1.3-28.1]
- bslib         [repo: RSPM -> CRAN; ver: 0.4.2 -> 0.5.1]
- cpp11         [0.4.3 -> 0.4.6]
- DiagrammeR    [1.0.9 -> 1.0.10]
- digest        [repo: RSPM -> CRAN; ver: 0.6.31 -> 0.6.33]
- dplyr         [1.1.2 -> 1.1.3]
- evaluate      [repo: RSPM -> CRAN; ver: 0.20 -> 0.21]
- fontawesome   [0.5.1 -> 0.5.2]
- foreign …
```
> update 34 packages

- episodes/05-data-structures-part2.Rmd
In the Realistic example section, the links to download gapminder_data.csv were broken. 
I replaced the old link (https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv) with the new working tested link (https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/main/episodes/data/gapminder_data.csv) on two occasions in episode 05-data-structures-part2.Rmd
> Update 05-data-structures-part2.Rmd to fix broken links to gapminder_data.csv

- episodes/01-rstudio-intro.Rmd
Removed excess language and re-ordered paragraphs for clarity. I removed jargon before it was defined (e.g. IDE) and removed repetitive language. I also clarified why R is a useful tool to learn compared to Excel or Sheets.
> Clarify motivation section text

- episodes/13-dplyr.Rmd
Closes #819 
The example I changed relied on implicit behavior of dataframes (which is often better to avoid and doesn't work on tibbles) so I made a slight change to the example that results in the same output but doesn't rely on the implicit dataframe behavior of converting a one column dataframe into a vector.
> Remove reliance on implicit df behavior, #819

- episodes/02-project-intro.Rmd
- episodes/08-plot-ggplot2.Rmd
- episodes/14-tidyr.Rmd
- episodes/15-knitr-markdown.Rmd
- learners/reference.md
Closes #875.
Minor fixes to avoid the "Unchanged files with check annotations" notification when reviewing PRs:
- added an alt-text to an image
- updated uninformative link texts
- fixed an anchor.
I am pretty confident the changes are ok, but maybe @skanwal or @naupaka could confirm it is fine before merging? Thanks!
> Minor fixes (missing alt-text, uninformative link text, missing anchor)

- episodes/05-data-structures-part2.Rmd
In the episode exploring data frames (https://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2.html), renaming row names is unnecessary as R re-names them sequentially. So, in the section 'Append to a data frame', the following code snippet can be removed.
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Closes #873
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of …
> Remove unwanted R code

- episodes/13-dplyr.Rmd
- episodes/14-tidyr.Rmd
Closes #856.
In the "Other great resources" links in two episodes:
- fixed the link to "R for Data Science" to point to the latest edition
- added a short description for each link (e.g. book/pdf file/online doc/video)
> Update/improve links to "Other great resources" in two episodes

- episodes/01-rstudio-intro.Rmd
Dear maintainers,
This PR follows from a closed PR found at [#868 ](https://github.com/swcarpentry/r-novice-gapminder/pull/868). As per advice from the maintainer team, I have added the proposed update via an instructor note.
I am a SWC Instructor who regularly delivers this R workshop to researchers. Over the course of many workshops in 2023, there have been recurrent issues in relation to lazy loading, and dependency install failure when installing ggplot2 on some machines. 9/10 times, setting the dependencies flag to TRUE explicitly tends to resolve the issues encountered. The other 1/10 times are often new R users setting the library download location to a sync folder i.e. cloud storage (in my experience at least).
For your consideration, and best wishes.
> Proposed Update to package install at 01-rstudio-intro.Rmd

- episodes/08-plot-ggplot2.Rmd
Replace `size` with `linewidth` for `geom_smooth()` example. Using `size` for lines was deprecated per this error message:
```
> ggplot(data=gapminder,
+        mapping=aes(x=gdpPercap,
+                    y=lifeExp)) +
+   geom_point(alpha=0.5) +
+   scale_x_log10() +
+   geom_smooth(method='lm', size=1.5)
`geom_smooth()` using formula = 'y ~ x'
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```
Change throughout the lesson and additionally:
1. Adjust language in explanations to match
2. Add hint to challenge clarifying size is point equivalent of linewidth.
3. Add some additional …
> Replace size with linewidth

- episodes/04-data-structures-part1.Rmd
Closes #901 
Changed `likes_string` variable in the `cats` data frame to `likes_catnip` instead. This should clear up a frequent point of confusion where learners interpret "string" as referring to a character data type. See further discussion/description in #901.
> Change "likes_string" to "likes_catnip"

- episodes/04-data-structures-part1.Rmd
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
Closes #717. The lesson `04-data-structures-part1` has been missing `feline-data_v2.csv` for some time without being added. The lesson says to read in this .csv and then use it for an exercise. Changed so that a `data.frame` is created rather than reading in the non-existent .csv.
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of …
> Add data in place of `feline-data_v2.csv`, closes #717

- episodes/04-data-structures-part1.Rmd
The `read.csv` function was used in the code block, however it was incorrectly referred to as `read.table`. I have changed the reference from `read.table` to `read.csv` to reflect the correct name of the function used in the code.
> Fix typo in Data Structures Part 1

- episodes/03-seeking-help.Rmd
This adds a new section to the "Seeking Help" episode, titled "Other ways to get help" that discusses searching the internet, StackOverflow, talking to another person, and generative AI chatbots e.g. ChatGPT as possible ways to get more help when faced with errors while coding. The existing material on StackOverflow and useful functions in R that help formulate a question (and reproducible example) was incorporated into this new section.
These changes are based on the [changes made to the python-novice-gapminder lesson](https://github.com/swcarpentry/python-novice-gapminder/pull/697) by @tobyhodges. I haven't made any major to changes to the text introduced there, I've just tried to incorporate it into the flow of this episode. 
Feedback welcome!
> Add content on generative AI to the "Seeking help" episode

- episodes/04-data-structures-part1.Rmd
This exercise is using the `cats2` object and therefore `cats2` should be printed to view the change and not `cats`
> cats2 should be printed not cats

- episodes/04-data-structures-part1.Rmd
Line 370 - Should be cats2 and not cats, based on the dataset that is being used in the exercise
> Change cats to cats2
