swcarpentry/r-novice-gapminder

CONDUCT.md
CONTRIBUTING.md

Copied the file CONTRIBUTING.md (and CONDUCT.md) from r-novice-inflammation.
This file explains that changes should be made to the markdown files in the gh-pages branch.

Adding file CONTRIBUTING.md

---

01-rstudio-intro.Rmd
02-project-intro.Rmd
04-data-structures-part1.Rmd
05-data-structures-part2.Rmd
06-data-subsetting.Rmd
07-functions.Rmd
08-plot-ggplot2.Rmd
09-vectorisation.Rmd
10-control-flow.Rmd
11-writing-data.Rmd
12-plyr.Rmd
instructors.md

Updated timings for all lessons 1-12 (if no change then old timing was correct). Added note to instructors.md about leaving time for technical difficulties.
Relates to #19

Updated timings for all lessons 1-12

---

OUTLINE.md

This outline file answers #12 and will hopefully help us discuss the content and structure of the lessons.
It contains the section headings of all documents.

adding outline file

---

03-seeking-help.Rmd
04-data-structures-part1.Rmd
05-data-structures-part2.Rmd
06-data-subsetting.Rmd
07-functions.Rmd
08-plot-ggplot2.Rmd
09-vectorisation.Rmd

I've added solutions for some challenges that didn't have them, and moved / copied solutions to the end of each lesson so they can be found easily. I'm not sure of the best way to make a separate page for challenges / solutions as suggested in https://github.com/swcarpentry/r-novice-gapminder/issues/23.
Note that moving the 08-plot-ggplot2 solutions to the end and formatting them in the same way as the other solutions means that some plots are no longer produced and included in the html - is this a problem?
(Also this is my first pull request here so please let me know if I'm doing anything incorrectly!)

Challenge solutions

---

10-control-flow.Rmd

Issue #27 
Might need a little more massaging. Let me know what you think.

Remove while

---

xx-why-R.Rmd

@mikabr and I (and maybe @hdashnow ) wanted to explore a more data- and demo-centric opening lesson. I grabbed a chunk of lesson 8; Mika made original contributions using dplyr and tidyr. The idea would be to make the existing 01 a new 02 (and so on). Questions:
- How does it feel to begin with a motivating example?
- Should we teach dplyr and/or tidyr, or should we replace those examples with something from packages already in the lesson?
- If we like this approach to lesson 1, should we move any of the later lessons towards this approach of less exposition, more payoff?
Finally, @aammd pointed out that we have an empty motivation.md slideshow which might serve as an alternate home for a gee-whiz demo.

Alternate start

---

07-functions.Rmd

This fixes some variation in the "what is a function" callout, and includes Sam's suggestions from #46

Resolving merge conflicts in Sam's modifications

---

.gitignore
01-rstudio-intro.Rmd

* enumerated list fix
* clearer delineation of alternative ways to accomplish actions
* brief mention of vectorization

Minor edits

---

03-seeking-help.Rmd

added a challenge concerning the `c` function

added a challenge to the help tutorial

---

04-data-structures-part1.Rmd

Seemed helpful to discuss `str()` at the outset.

Added `str` to list of data type interrogations

---

06-data-subsetting.Rmd

* typos and cleanups
* tip: vector numbering starts at 1
* tip: vector names need not be unique
* added mention of "byrow" option when creating a matrix

minor fixes and additions

---

09-vectorisation.Rmd

Most substantive changes:
* removed references to ggplot2 (to facilitate using this lesson earlier in the sequence)
* revised the treatment of challenge 4 to focus on vectorization

Minor edits.

---

02-project-intro.Rmd

Only `.Rmd` file changed, not sure how-to, or who's responsible for, the `.md` and `.html` version.

Simplifies download of raw gapminder data to fix issue #72.

---

.mailmap
Makefile
_includes/javascript.html

Can now include equations in SWC R lessons. For details, see https://github.com/swcarpentry/lesson-template/pull/286

Add mathjax support

---

06-data-subsetting.Rmd

Added challenge question to check learner's understanding of "which" & empty vectors and shows
example of common bug when using "which" to subset

Added challenge question

---

06-data-subsetting.md

Exercise for instructor training regarding subsetting using multiple logical operators and introducing the unique() function

New challenge regarding subsetting, logical operators and the unique() function

---

01-rstudio-intro.Rmd
02-project-intro.Rmd
03-seeking-help.Rmd
04-data-structures-part1.Rmd

I've added some more challenges according to #22

More challenges

---

04-data-structures-part1.Rmd
05-data-structures-part2.Rmd

Hi folks - this PR remixes sections 4 and 5 (intro to data types and data structures), following the pattern tested out by @lmguzman [at UBC](http://lmguzman.github.io/2016-01-29-UBC/index.html) and myself  [at ResBaz SFU](http://bgran.de/2016-02-02-SFU/) over the past week; the core motivation is to **introduce types and structures by exploring the data.frame**.
Understanding types and structures is crucial for successfully wielding R - the problem being, that beginners really struggle to see why this is so, and are often turned off by how dry the topic seems. Instead of marching them through a gallery of types and structures, this method starts by loading a csv right away, and performing common manipulations which quickly lead to illustrations and conversations on why data types exist, …

reimagining data types and data structures

---

04-data-structures-part1.Rmd

Proposed challenge for the instructor training wrap up

Add challenge about matrices

---

09-vectorisation.Rmd

The solutions to challege 2 in the vectorisation page use base graphics, but the visualization page shows learners `ggplot()`. I updated the Rmd to use `ggplot()` to produce the solution.

Changed solution to Challenge 2 to use ggplot()

---

reference.md

Issue #62 
I kept a lot of the original information on data types and structures although the new data structure material presents it in a different format as I think it makes a great summary resource.

Updated reference.md to reflect new lesson structure

---

04-data-structures-part1.Rmd
data/feline-data_v2.csv

Addressed issue #111 - Asking users to manually modify a data file caused inconsistent output in the html.
Also issue #110 (duplicate headers) while I was in the file.

Modified data file for 04-data-structures-part1

---

01-rstudio-intro.Rmd

Hey @naupaka 
Please find this new pull request updated so that there is only the .Rmd file that has been changed.
Thank you for your time.
Sincerely,
Marc

added solutions to Challenges in Intro to R and RStudio Rmd Only

---

08-plot-ggplot2.md

Add alpha function description to Challenge 5.

Add alpha function description

---

06-data-subsetting.Rmd

Addresses #106
Adding a solution to challenge 3, and making sure 'print' object is called x_subject. 
Did this again to fix merging issues.

add solution to chal. 3 lesson 6 data subsetting

---

01-rstudio-intro.Rmd

Addresses #49. Adds motivation to introduction for scientists, ties in programming objectives to data analysis. Mentions plots earlier.

add-motivation-to-gapminder-lessons

---

05-data-structures-part2.Rmd

Now shows the data frame with the garbage row, and adds a note suggested by #113 on how to remove multiple rows from a dataset.
fixes #113

Improvements for garbage row in Data Structures Part 2

---

04-data-structures-part1.Rmd
05-data-structures-part2.Rmd

This closes #95 . Includes Andy's changes and makes a few minor editorial tweaks

Rm subset from data aammd

---

index.md
instructors.md

Tom's prerequisites 

---

index.md
instructors.md

Address issue #48, update shell requisite and drop git requisite.

BUGBBQ: Improve prerequisites

---

07-functions.Rmd
15-wrap-up.Rmd
index.md
reference.md

Addresses issue #62 errors in make check.
I suggest the missing glossary in reference.md is opened as a new issue as this is a much larger piece of work.

Update link text to remove make check errors

---

06-data-subsetting.Rmd
08-plot-ggplot2.Rmd

Just adding a solution to challenge 3 to make more in line with other challenges.

Solution to challenge 3

---

05-data-structures-part2.Rmd

- add solution to Challenge 3
- change reference to xlsx package to Hadleyverse readxl
- give example of reading a csv file from https
- update example discusssing tsv

Edits to 05-data-structures-part2

---

02-project-intro.Rmd

Add tip which references "Good Enough Practices for Scientific Computing" by Greg Wilson et al.
Not included in this PR, but perhaps the reference to ProjectTemplate should be removed?

Reference Good Enough Practices for Scientific Computing

---

07-functions.md

Added an easy challenge (Challenge #4) to address issue #22:  Add more easy challenges

Added an easy challenge to lesson 7 (functions)

---

index.md
reference.md

Fixed errors occurring during `make check`.

Fix checks

---

02-project-intro.Rmd

I added solutions to Challenges 2 and 3 of `02-project-intro`. Challenge 1 didn't require a solution.

Project intro solutions

---

04-data-structures-part1.Rmd

- Add note on editing text files (csv) within R
- Add note relating data frames to lists
This is like #144 without the find and replace of data.frame.

Edit 04-data-structures-part1.Rmd

---

10-control-flow.Rmd

Added solutions for the first two challenges.

Added solution Challeng 1,2

---

01-rstudio-intro.Rmd
04-data-structures-part1.Rmd
06-data-subsetting.Rmd
08-plot-ggplot2.Rmd
10-functions.Rmd
12-plyr.Rmd
14-tidyr.Rmd

Purge instances of the word just from the lessons

Remove just

---

04-data-structures-part1.Rmd

Just some minor typos and some rephrasing to result more readable.

minor rewordings

---

instructors.md

Add section on setting up git in RStudio for Mac OS X and Windows users

---

04-data-structures-part1.Rmd

I found working through the data frame addressing examples in 04-data-structures-part-1 to be very valuable. I think it is worth promoting this to a challenge.
Writing the solution was not as easy as I anticipated. If anyone has suggestions for clarification I'm happy to hear them.

Converted data frame addressing examples to a challenge.

---

_episodes_rmd/04-data-structures-part1.Rmd

The data are entered at 0, 1 but the text is shown as TRUE, FALSE. This doesn't happen until the example using `as.logical` on line 304 when it's coerced.

Correct the "likes_string" column

---

_episodes_rmd/01-rstudio-intro.Rmd

Partial fix for the issue of referencing data before showing how to download (raised downthread in #172 )

Link refererence to data in setup to gapminder.org

---

_episodes_rmd/07-control-flow.Rmd

In this pull request I add solutions to the gapminder challenges in the 07-control-flow lesson. We use a for loop and if-else statements to loop over each continent or country to calculate life expectancy, and print out statments about the life expectancy (and plot a graph).
I use unique and subset commands, which the students should have seen so far in the R sessions.  I also use grep and cat which should be familar from the Unix Shell.
I only "go in" two deep, one loop, one if-else, because we want to keep the code easy to read, which becomes hard if there are three or more levels of indentation and consequent code
PS. This pull request is part of Instructor Training

Addition of solutions to 07-control-flow, gapminder challenges

---

_episodes/05-data-structures-part2.md

"Duplicate" of #216. Instead of rebuild the file this only revert the "bad" commit.

Add missing _episodes/05-data-structures-part2.md back

---

_episodes_rmd/07-control-flow.Rmd

set.seed() is mentioned in the description of what will be done prior to the code chunk and is then further explained in more detail after the code chunk. For learners to fully understand how the function is used it should be shown in action.

added set.seed() in lesson 07, code chunk line 68

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/04-data-structures-part1.Rmd

Two quick fixes for issues #194 and #218. Not sure about the etiquette re: these being one PR or two separate PRs. Cheers!

Fixes for #194 and #218

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/05-data-structures-part2.Rmd
_episodes_rmd/06-data-subsetting.Rmd

This pull request makes some minor formatting changes to fix: 
- Issue #183 - numbered list not rendering correctly in Challenge 7, lesson 7
- Issue #189 - Avoiding use of c() before it is introduced in lesson 1 Challenge 5
- Issue #211 - splitting data.frame commands to avoid long lines in lesson 5 Challenge 1 and solution
I'm a newcomer doing this as part of my instructor training.  I haven't run the make file to regenerate the md files.  Please let me know if I should also do this.
Helen

Fixes for issues #183 #189 and #211

---

_episodes_rmd/05-data-structures-part2.Rmd

When going through the lesson for the first time, when it came time to
remove a 'garbage row', I wasn't sure where it came from! I have tried
to add more explanation why the garbage row was created, when it was
created.
(SWC training checkout)

add detail to why 'garbage row' appears

---

_episodes_rmd/13-dplyr.Rmd

Added solutions for the second part of the challenge, as suggested in issue #230.
I've added solutions with and without the use of `arrange()`, as learners haven't seen this function during the lesson.

added two possible solutions to dplyr challenge 2

---

_episodes_rmd/05-data-structures-part2.Rmd

+Extended the objectives to reflect specific lesson content.
+Added headers to subset material
+Removed redundant examples

Lesson 05 - extend objectives + add headers

---

_episodes/13-dplyr.md

Add a short example showing how `dplyr` and `ggplot2` can be used together, as
discussed in #174. The example takes the facet plot from the plotting episode
that required new variables and shows how it can be made using `dplyr`.
Fixes #174.

Add ggplot example to dplyr episode

---

_episodes_rmd/04-data-structures-part1.Rmd

Fix L suffix as proposed by @rgaiacs

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/02-project-intro.Rmd
_episodes_rmd/03-seeking-help.Rmd
_episodes_rmd/04-data-structures-part1.Rmd
_episodes_rmd/05-data-structures-part2.Rmd
_episodes_rmd/08-plot-ggplot2.Rmd
_episodes_rmd/10-functions.Rmd

As the commit message says, these are mostly minor typos.  In a few places I didn't manage to restrain myself from making stylistic changes, plus there is a little bit of new material in solutions to some of the challenges.

mostly typos, some stylistic, some challenge solutions

---

_episodes/08-plot-ggplot2.md
_episodes/14-tidyr.md
_episodes_rmd/02-project-intro.Rmd
_episodes_rmd/09-vectorization.Rmd
_episodes_rmd/11-writing-data.Rmd
_episodes_rmd/12-plyr.Rmd
_episodes_rmd/13-dplyr.Rmd
_episodes_rmd/14-tidyr.Rmd
_episodes_rmd/15-knitr-markdown.Rmd

Also took opportunity to remove quotes in library calls, for consistency.
And a link to r4ds.had.co.nz

Quoted all calls to library() and added [R for Data Science](r4ds.had.co.nz) links

---

_episodes/03-seeking-help.md
_episodes_rmd/03-seeking-help.Rmd

clearer explanation of difference between sep and collapse

---

_episodes_rmd/13-dplyr.Rmd

I'm definitely open to a better suggestion for the demonstration of `n()`

[fix #231] mention count() and n()

---

CONDUCT.md

Revert "Remove CONDUCT.md since it should be generate by bin/lesson_initialize.py"

This reverts commit 1e56203d492a1a13d86756fb5e9d754ed2cae0f8.

---

_episodes/13-dplyr.md
_episodes_rmd/13-dplyr.Rmd

This PR suggests a slight extension for session 13: dplyr. It introduces the combination of 'mutate()' with 'ifelse()', just after the regular mutate-block, in order to expand thinking about how creating new values can be logically influenced right from its creation. It includes 2 examples pointing in 2 different directions of usage: 1) a different approach and an inclusion of 'filter()' and 2) a conditional updating of values.

introduce mutate() in combination with logical filtering: ifelse()

---

_episodes_rmd/05-data-structures-part2.Rmd

two small typo fixes

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/12-plyr.Rmd
_episodes_rmd/13-dplyr.Rmd

Some minor typo fixes and text edits to complete Instructor Training:
Lesson 1: 
a) "the" 
b) editing for clarity
Lesson 12: calcGDP typo
Lesson 13: use --> us

typo fixes and minor text edits

---

CONTRIBUTING.md
_episodes_rmd/05-data-structures-part2.Rmd

I've added a challenge to lesson 05 in response to [issue 266](https://github.com/swcarpentry/r-novice-gapminder/issues/266)

added as.numeric(factor) challenge

---

_episodes/13-dplyr.md

This is in reference to Issue #297.

Add a note about tibbles to the dplyr lesson

---

_episodes_rmd/02-project-intro.Rmd

This pull request is to update the advice in episode 2 about running R code from a script rather than a console. It is in reference to issue [#301](https://github.com/swcarpentry/r-novice-gapminder/issues/301).

Updated advice about writing code in script rather than console

---

_episodes_rmd/13-dplyr.Rmd

Here I would suggest increasing the number of learning objectives for this lesson, making them a little more granular.  I also added an example showing how several summary statistics can be calculated together, which may have not been apparent from the original lesson.

Episode 13 learning objectives

---

_episodes_rmd/11-writing-data.Rmd

In 11-writing-data.Rmd the proposed solution to challenge #1 used "p" without first assigning to it. This fixes that bug.

Fixed bug in challenge #1 solution

---

_episodes_rmd/10-functions.Rmd
_episodes_rmd/11-writing-data.Rmd
_episodes_rmd/13-dplyr.Rmd
_episodes_rmd/14-tidyr.Rmd

The purpose of this PR is to add material related to using defensive programming effectively when writing functions in R, at an elementary level. To that end, a section has been added to lesson 10 ("Functions Explained"), introducing defensive programming as a concept and illustrating how it may be used to improve a set of functions defined earlier in that lesson by adding in `stopifnot` to check argument conditions (prior to this, conditional statements for this purpose are also introduced). The material added is adapted from the excellent (more thorough) Software Carpentry lesson on "Intermediate Programming with R" (the particular lesson is available [here](https://jdblischak.github.io/r-intermediate-altmetrics/23-stopifnot.html)). As this PR resolves #221 (at least in part; perhaps …

Defensive programming section in lesson on functions

---

_episodes_rmd/05-data-structures-part2.Rmd

Fixing issue #319 by replacing link to broken page with link to working alternative page.

Issue #319 Update link to working webpage

---

_episodes_rmd/07-control-flow.Rmd

Replaced rpois line with x<-8
removed settled
Removed tip relating to rpois
added an extra example with if/else only

removed rpois and setseed

---

_episodes/05-data-structures-part2.md
_episodes_rmd/05-data-structures-part2.Rmd

Hello!
I'm sending a PR for a new challenge adding the use of tail() and how to get a few random rows from a data frame in the episode 05-data-structures-part2.Rmd.
The main reason behind it is to get students to think a little bit more when checking data frames and not settling with the first few lines only. I think it is better practice, but may add to an already full session. 
Happy to hear any thoughts even if the changes are not accepted.
Thanks in advance,
Antonio

instructor checkout challenge added 05-data-structures-part2.Rmd

---

_episodes_rmd/05-data-structures-part2.Rmd

This change makes it easier to learn as students are not first presented with an incorrect example. It still allows for understanding the error as the negative model (M-) comes second, then the positive answer (M+) is re-enforced at the end as it is stored while overwriting 'cats'. It also has the advantage of not teaching bad data handling practices ("if the data set doesn't work, change the data set till the technique works").

Change the 'adding columns' part of the lesson to follow M+ M- M+ format

---

_episodes_rmd/05-data-structures-part2.Rmd

as requested https://github.com/swcarpentry/r-novice-gapminder/pull/336

added an s for directory scripts

---

_episodes_rmd/01-rstudio-intro.Rmd

This updates episode 01 to use the HTML `<kbd>`  tag.

Use kbd formatting in episode 01

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/07-control-flow.Rmd
_episodes_rmd/10-functions.Rmd
_episodes_rmd/12-plyr.Rmd

Addressed an outstanding issue as part of instructor training.

Moved PR changes (#326 #327 #328) made in md to Rmd (close #339)

---

_episodes/000_DO_NOT_EDIT_FILES_IN_THIS_DIRECTORY_README_FOR_MORE_DETAILS.txt

This PR adds a file to episodes/ which points contributors to episodes_rmd/ as the correct place to make changes in the R lesson.

Add a file pointing contributors to the correct location to make lesson changes

---

README.md
_extras/guide.md
index.md

This includes some of the paths through the material  that were suggested in issue #104 in the instructor guide

Include outline lesson plans

---

_episodes_rmd/01-rstudio-intro.Rmd

Adding a short note referring to the misconception of physicists when hearing about vectors in R

Issue#334 short note about vectors in R in contrast to physics

---

_episodes_rmd/08-plot-ggplot2.Rmd

Changed original objective (To understand the basic grammar of graphics, including the aesthetics and geometry layers, adding statistics, transforming scales, and coloring or panelling by groups") to more measurable verbs: apply, manipulate, improve

fix objectives 08-plot-ggplot2

---

_episodes_rmd/05-data-structures-part2.Rmd

factors *are* vectors (can be verified by testing a factor x with `is.atomic(x) || is.list(x)` as per http://adv-r.had.co.nz/Data-structures.html)

fix one erratum

---

_episodes_rmd/05-data-structures-part2.Rmd

No major change:
- remove unnecessary and repetitive "be able to" in objectives
- rephrase several sections
- add spaces after comma, following Hadley's recommendations
- change single quotations to double quotations

Wording edits

---

_episodes_rmd/05-data-structures-part2.Rmd

Please delete the text below before submitting your contribution. 
---

Add section demonstrating how to remove columns from a df

---

_episodes_rmd/06-data-subsetting.Rmd

fixed a typo: there was a double 'to' in Section 'Skippng and removing elements'

fixed typo

---

_episodes_rmd/08-plot-ggplot2.Rmd
_episodes_rmd/12-plyr.Rmd
_extras/guide.md

renames the ggplot2 and plyr episodes in the Rmd files and the guide as per suggestions in issue #366

rename ggplot2 and plyr episodes

---

_episodes_rmd/02-project-intro.Rmd
_episodes_rmd/15-knitr-markdown.Rmd

Please see the diff & https://github.com/swcarpentry/git-novice/pull/478 ;-)

Improve link text for screen readers

---

_episodes_rmd/02-project-intro.Rmd

As per the discussion on issue #379, the following tip will be transferred to a more advanced section ([Writing Good Software](https://swcarpentry.github.io/r-novice-gapminder/16-wrap-up/))

Remove ProjectTemplate tip

---

_episodes_rmd/04-data-structures-part1.Rmd

The output shown after the toy dataset creation is not shown to the user unless they view the `feline-data.csv` file. This text tries to makes that clear.

Make it clear csv output is from feline-data.csv

---

_episodes_rmd/10-functions.Rmd

Issue #368

---

_episodes_rmd/10-functions.Rmd

'commit --amend' Added clarification to function creation

---

_episodes_rmd/08-plot-ggplot2.Rmd

introduce ggsave

---

_extras/guide.md

link to this https://github.com/swcarpentry/r-novice-gapminder/issues/410
@naupaka

update gapminder_data.csv path

---

_episodes_rmd/06-data-subsetting.Rmd

question 4 in challenge 7 gave the wrong column names, should be (`continent` and `lifeExp`)
Please delete the text below before submitting your contribution. 
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would …

Fixed mistake in challenge 7

---

_episodes_rmd/05-data-structures-part2.Rmd

With regards to #439 - change suggested by @jcoliver .

Change challenge 1 description.

---

_episodes_rmd/14-tidyr.Rmd

Deduplicate word

---

_episodes_rmd/05-data-structures-part2.Rmd

Added a brief description and example of the summary() function to 05-data-structures-part2.Rmd. This addresses issue #445

Updated 05-data-structures-part2 with summary() function

---

_episodes_rmd/07-control-flow.Rmd

Some edits designed to address ambiguity for the lesson on while statements and also to align the wording with common approaches to discussing entry controlled flow statements. 
This addresses r-novice-gapminder issue 459:
https://github.com/swcarpentry/r-novice-gapminder/issues/459

while statement clarifications

---

_episodes/06-data-subsetting.md
_episodes_rmd/06-data-subsetting.Rmd

Fixed formatting problem is stated in https://github.com/swcarpentry/r-novice-gapminder/issues/464

Fixed formatting in episode 06, challenge 7

---

_episodes_rmd/07-control-flow.Rmd

Hello, I made some changes to the exercises in  Episode 7 (control flow) per issue #460 that I had created. I introduced `cat()` earlier in the lesson so users would have seen it once already prior to the exercise. I left in the final use of `mean` and `subset` in final exercise thinking that if advanced users make it to that exercise, it will be a nice challenge.

simplify 07-control flow exercises

---

_episodes_rmd/03-seeking-help.Rmd

I wasn't sure how to make a tip list, so it could be that this can be pulled into a list with the other tip on R functions.

Tip: Running examples with ctrl+enter

---

_episodes_rmd/08-plot-ggplot2.Rmd

In response to issue #473 I have implemented changes in the code to all instances of aes() in the rmd files of the ggplot2 lesson. https://github.com/swcarpentry/r-novice-gapminder/issues/473

added mapping =  argument before aes() per issue #473

---

_episodes_rmd/08-plot-ggplot2.Rmd

This addresses the issue here https://github.com/swcarpentry/r-novice-gapminder/issues/484

Change blank axis in 08-plot-ggplot to rotated form

---

_episodes_rmd/14-tidyr.Rmd
_episodes_rmd/15-knitr-markdown.Rmd

And correct a typo in episode 14.

Update learning objectives of episode 15

---

setup.md

Listed the packages that will be downloaded and installed during the lesson to the setup inatructions. This is helpful in situations where IT staff need to be informed about the packages installed on the computers.

Added links to packages used in the lesson

---

setup.md

Update setup.md to fix grammar

---

_episodes_rmd/12-plyr.Rmd

Add solutions to plyr challenges

---

_episodes_rmd/15-knitr-markdown.Rmd

Add solutions for knitr challenges

---

_episodes_rmd/12-plyr.Rmd

Minor formatting fix to pull text out of R code chunk.

Fix solution formatting for plyr challenge 1

---

_episodes_rmd/15-knitr-markdown.Rmd

Take 2 on fixing chunk formatting in challenge solutions

Knitr solutions

---

_episodes_rmd/15-knitr-markdown.Rmd

Trying again using https://yihui.name/knitr/faq/ and https://rmarkdown.rstudio.com/articles_verbatim.html

Attempt to fix chunk formatting in solution

---

_episodes_rmd/08-plot-ggplot2.Rmd

Checkout and first addition. Attempting to address issue https://github.com/swcarpentry/r-novice-gapminder/issues/480

Change scale_x_log10 ggplot option to scale_x_continuous in episode 8 #480

---

_episodes_rmd/13-dplyr.Rmd
_episodes_rmd/14-tidyr.Rmd

Because those topics/operations are comparably complex, please help make the code easier on readers. I added whitespace around `=` and after `,` as RStudio's `Reformat code` shortcut or [styler](https://github.com/r-lib/styler) would.

Improve code legibility in 13-dplyr & 14-tidyr

---

_episodes_rmd/09-vectorization.Rmd

Resolves #523 .
Ps 1. This is my first PR. I'm not sure how much from the discussion on the issue I should duplicate in the PR.
Ps 2. Should I commit the changes to the `.md` file as well?

Add for loop example for comparison with vectorized code

---

_episodes_rmd/13-dplyr.Rmd

---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate …

fix text inconsistency for dplyr functions

---

_episodes_rmd/04-data-structures-part1.Rmd

Corrected inconsistent spacing weight vector of cats dataframe so the weight vector is spaced consistently with the coat and likes_string vectors.

corrected inconsistent spacing in weight vector

---

_episodes_rmd/07-control-flow.Rmd

Added consistent spacing, explanation of ifelse error based on length of input vector, and advice on what to use if iteration order doesn't matter.

spacing, ifelse, and vectorized changes 

---

_episodes_rmd/07-control-flow.Rmd

Removes duplicate sentence flagged in Issue #578 .

Issue #578: remove duplicate sentence

---

_episodes_rmd/07-control-flow.Rmd

Added a short tip on the usefulness of R's built-in ifelse() function, including the syntax and an example usage.

Added tip on R's build-in ifelse() function!

---

_episodes_rmd/08-plot-ggplot2.Rmd

Change challenge 5 from density plot to boxplot

challange 5 - boxplot

---

_episodes_rmd/08-plot-ggplot2.Rmd

This seems to belong to #117 ;-)

Update scale_x_log10 docu to match code

---

_episodes_rmd/14-tidyr.Rmd

This may have [slipped through #583](https://github.com/swcarpentry/r-novice-gapminder/pull/583/files#diff-e9ab8aaeede8d38feec79475cd427a2cR163). If so, apologies for not catching it either! cc @matt-dray

Follow-up to pivot_longer/_wider() update

---

_episodes_rmd/08-plot-ggplot2.Rmd

See diff ;-) These are the current links that RStudio also uses.

Update ggplot2 docu & cheatsheet links

---

_episodes_rmd/05-data-structures-part2.Rmd

Mentioning as.character to make it more explicit, hopefully the wording is good enough.
closes #575

Explicit mention of as.character for chapter 5 challenge 1

---

_episodes_rmd/14-tidyr.Rmd

An attempt at adding some revised text around the `tidyr::pivot_longer()` and `pivot_wider()` functions, plus a few offered minor edits. This PR is a contribution to this [issue](https://github.com/swcarpentry/r-novice-gapminder/issues/594). I hope this is a start and helps the lead authors and community land on something helpful for novice learners.

WIP: revise pivot_*() language  (closes #594)

---

_episodes_rmd/08-plot-ggplot2.Rmd

I've done what was suggested at https://github.com/swcarpentry/r-novice-gapminder/issues/611#issuecomment-577791372
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the …

hoping to fix style on challenges 4b and 5

---

_episodes_rmd/01-rstudio-intro.Rmd

Fix typos in intro episode

---

_episodes/01-rstudio-intro.md
_episodes/05-data-structures-part2.md
_episodes/08-plot-ggplot2.md
_episodes/12-plyr.md
_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/05-data-structures-part2.Rmd
_episodes_rmd/08-plot-ggplot2.Rmd
_episodes_rmd/12-plyr.Rmd

For issue #617
Occasional usage of "simply" in 4 episodes were removed or changed to other words.

Removed usage of "simply"

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/02-project-intro.Rmd

Minor text edits to the Intro section to resolve issue #599 .

Standardize articles preceding '.R' and expand description of help pane

---

fig/13-dplyr-generate-figures.R

- Figures were redrawn to avoid overlapping arrows to eliminate potential confusion.
- Colors were also changed in order to be colorblind safe.

Issue #581 fix. Figures redrawn

---

_episodes_rmd/05-data-structures-part2.Rmd
_episodes_rmd/06-data-subsetting.Rmd

Further resolving Issue #561, I added a link to the "Subsetting through other logical operations" within episode 06.

added link and note about logic operators in episode 06 #561

---

_episodes_rmd/05-data-structures-part2.Rmd

The phrase sanity check is ableist, and is easy to fix! For more details: https://gist.github.com/seanmhanson/fe370c2d8bd2b3228680e38899baf5cc

remove ableist language

---

_episodes_rmd/16-wrap-up.Rmd

Fixed duplicate entry in the section keypoints for episode 16

Fixed duplicate entry in the section keypoints for episode 16

---

reference.md

updated tidyr functions in the reference

Update tidyr functions in the reference

---

_episodes_rmd/04-data-structures-part1.Rmd

It's an update of learning objectives, using the suggested frame “Learner will be able to do X” (rather than the intangible “Learner will be aware of X”). The verb “identify” has been chosen among Bloom's taxonomy verbs.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson …

Update of 04-Data-Structures learning objectives

---

_episodes_rmd/13-dplyr.Rmd

I have amended the example code to include spaces in between the selected variables to make it neater and more readable.

Neat code up with spaces

---

_episodes_rmd/10-functions.Rmd

Updating one link in function lesson, in lieu of #551

Update link in function lesson

---

_episodes_rmd/03-seeking-help.Rmd

Closes issue #657 by submitting pull request for suggested idea. I edited the suggestion in the issue for additional clarity. 
Before content:
After content: (doesn't look exactly the same bc of the way I knit the document, should show up normally in lesson)
Added lines 87-92:

Define fuzzy search in episode 3 (seeking help)

---

CITATION
README.md

proposing updates to citation documentation as described in #530. should close #530.

updating CITATION and Readme.md with new Zenodo citation info

---

_episodes_rmd/03-seeking-help.Rmd

Good evening,
This pull request contains changes to address the following issues:
- #682 issue
- That for special operators, backticks also can pull up the help page
- If Stack Overflow is going to be mentioned, I think its "how do I ask a good question?" page should be referenced/encouraged to be read. Stack Overflow can be an intimidating place for new users to navigate, and some users not kind to those who do not follow the community protocol.
- I fixed "Tip: Running Examples" which had its callout box broken.
Thank you for the great repository. I am quite excited to try teaching with this one.

#682 + a few more additions

---

_episodes_rmd/09-vectorization.Rmd

made changes recommended in https://github.com/carpentries/carpentries.org/issues/993  for accessibility purposes.

removed contractions

---

_episodes_rmd/15-knitr-markdown.Rmd

Hi,
I did a quick read through of the `knitr` lesson and noticed some spelling mistakes. I also made some wording changes that I think make the text clearer.
The only major change was to remove the text at line 110 because I couldn't see what it was referring to in the document. Maybe I missed something.
Hope this helps! Let me know if I can change anything.

Minor text edits for spelling & clarity

---

_episodes_rmd/07-control-flow.Rmd

- use spaces consistently around operators
- else directly after closing braces
- use code style for object name in prose
- various typos
- fix location of comment
<details>
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about …

consistent style; typos; comment location

---

_episodes_rmd/02-project-intro.Rmd
_episodes_rmd/13-dplyr.Rmd
_episodes_rmd/14-tidyr.Rmd
_episodes_rmd/15-knitr-markdown.Rmd

Add alt-text to figures
Additions derived from Carpentries core team acc-athon. Please feel free to improve upon these as desired.

Add alt-text to 13dplyr.Rmd

---

_episodes_rmd/08-plot-ggplot2.Rmd

Adding alt-text for some illustrations in the lesson that were suggested by @kmomar in the Core Team Accessibility session. Ready for review.

alt-text suggestions for some illustrations

---

_episodes_rmd/12-plyr.Rmd

Small changes to plyr lesson, in large part to test site building.

Minor typo fix to plyr lesson

---

_episodes_rmd/08-plot-ggplot2.Rmd

A comma needed to be inserted in the chunk option

fix build error

---

_episodes_rmd/08-plot-ggplot2.Rmd

This fixes build errors due to missing commas

fix more commas -_-

---

_episodes_rmd/15-knitr-markdown.Rmd

Made a small edit to the knitr lesson based on #701 to mention `tinytex` in the tip for working with pdf documents. Feel free to improve as needed!

Include tinytex tip

---

_episodes_rmd/01-rstudio-intro.Rmd

typo correction

---

_episodes_rmd/13-dplyr.Rmd

This pull addresses issue #723 . The section now builds on the example used for the ggplot lesson on [Multi-panel figures](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/index.html#multi-panel-figures).

Update on "Combining dplyr and ggplot2" - Issue #723

---

_episodes_rmd/13-dplyr.Rmd

Revised a typo and added more examples to help learners to practice using the functions: select(), filter(), arrange(), and mutate()

R-novice-gapminder Update 13-dplyr.Rmd (checkout)

---

setup.md

For web accessibility purposes, rewrote so that the links are meaningful.

add meaningful links

---

_episodes_rmd/10-functions.Rmd

Hi,
I'm opening this pull request following the positive response in issue #740.
Hope this contribution is useful for the lesson.
Best,
Joselyn

Add the general structure of a function

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/06-data-subsetting.Rmd
_episodes_rmd/07-control-flow.Rmd
_episodes_rmd/13-dplyr.Rmd

resolves #746 
there were a few missing/extra spaces that affected the formatting of challenges and callout boxes. 
Thank you @marklcrowe for reporting these issues.

fix formatting issues

---

_episodes_rmd/14-tidyr.Rmd

changed capitalization to read Data Frame like in all other titles

capitalization

---

_episodes_rmd/01-rstudio-intro.Rmd

Removed the spacing in "work flow" and add a description of what a .R file and an R script it in line with the issue: https://github.com/swcarpentry/r-novice-gapminder/issues/758
<details>
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any …

Fixed typo and added description of R scripts

---

_episodes_rmd/13-dplyr.Rmd

Following the approved suggestion from #719 I introduced into dplyr module a mention of Tidyverse family of packages as a tip. I hope this will be useful for the students.

Added note on tidyverse

---

_episodes_rmd/15-knitr-markdown.Rmd

per issue #752, updated links with working addresses.

URL fix. Closes #752.

---

_episodes_rmd/02-project-intro.Rmd

Adding a short introduction to `getwd` and `setwd`, and RStudio menu options for checking and setting the working directory. #755 #276 #332

adding short intro to getwd and setwd

---

_episodes_rmd/02-project-intro.Rmd

Making change from issue #768

---

_episodes_rmd/01-rstudio-intro.Rmd
_episodes_rmd/03-seeking-help.Rmd
_episodes_rmd/04-data-structures-part1.Rmd

This PR is to address #773. 
I've added more explanations (some in the Challenges section) and more code chunk examples in several episodes (Intro to R, Seeking Help and Data Structures) so that learners can build on prior knowledge of using functions and calling arguments in Data Structures. For detailed discussion see #733

More stepping stones on using arguments and functions: Intro to R, Seeking Help + Data Structures

---

_episodes_rmd/10-functions.Rmd

Pull request for issue Functions Explained: Briefly Mention Packages #790

Functions Explained: Briefly Mention Packages #790

---

_episodes_rmd/08-plot-ggplot2.Rmd

Added alt text contributed by Toby Hodges for https://swcarpentry.github.io/r-novice-gapminder//fig/rmd-08-lm-fit-1.png, https://swcarpentry.github.io/r-novice-gapminder//fig/rmd-08-lm-fit2-1.png, https://swcarpentry.github.io/r-novice-gapminder//fig/rmd-08-ch4a-sol-1.png, https://swcarpentry.github.io/r-novice-gapminder//fig/rmd-08-ch3-sol-1.png

added alt text

---

_episodes_rmd/08-plot-ggplot2.Rmd

Changed two occurrences of "publication quality" to "publication-quality" for consistency in this document.
(Done as part of the checkout process).

Improved consistency

---

_episodes_rmd/13-dplyr.Rmd

Following up on #719 and #748 
Added a small amount of additional text to denote these packages are designed to work together (from https://tidyverse.tidyverse.org/). Also added a hyperlink for the tidyverse website.

Updated note on Tidyverse and added hyperlink

---

_episodes_rmd/09-vectorization.Rmd

added section on vector recycling to 09-vectorization.Rmd

---

_episodes_rmd/04-data-structures-part1.Rmd

This is a proposal to restructure some of the lesson about data types. I had the feeling that several things are more complicated than nessecary. I list them below. I have also split up the changes into separate commits that contain some rationale. 
I am unexperienced in the carpentries style of teaching, so if some of these changes contradict some of the best practices, I appreciate if you tell me so that I realize where my own teaching intuition contradicts approaches taken by the carpentries community. 
-----------------------------------
From my subjective perspective, the lesson has the following problems:
* Factors are not necessary for beginners. Most of the time they behave unintuitively and the best is if beginners learn how to avoid them as much as possible. Two packages `vctrs` …

Lession 4: Remove factors, simpler lists, dedicated names, separate typeof and class, data cleanup challenge. 

---

_episodes_rmd/08-plot-ggplot2.Rmd

This is a PR fixing the merge conflicts arising from #552.
It should allow for a clean merge of the content of #552 into main.

Fix merge conflicts for PR #552

---

_episodes_rmd/07-control-flow.Rmd

This will help me address the warning from https://github.com/carpentries/lesson-transition/issues/78

fix missing block quote symbol

---

episodes/07-control-flow.Rmd

As this lesson references loops from the shell lesson, this PR adds a link directly to that lesson.

include link to loops in shell lesson

---

episodes/07-control-flow.Rmd

As this lesson references `grep` and finding things from the shell lesson, this PR adds a link directly to that lesson.

add link to finding things in shell lesson

---

episodes/15-knitr-markdown.Rmd

Closes #861.
Fixed the issue with subscript markup noticed by @maneesha using the suggestion from @zkamvar.

Fix subscript markup (based on comments by @maneesha and @zkamvar)

---

instructors/instructor-notes.md

_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and …

add instructor note, closes #870

---

instructors/instructor-notes.md

The episode number, for Producing Reports With knitr, in the instructor notes is incorrect in two places.

Change episode number to 14 to Producing Reports With knitr

---

README.md

This adds me to the README as a maintainer :)

Add Craig Gross as maintainer
